apiVersion: v1
kind: Service
metadata:
  name: coroot
  namespace: coroot-dev
spec:
  selector:
    app: coroot
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coroot
  namespace: coroot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coroot
  template:
    metadata:
      labels:
        app: coroot
    spec:
      containers:
        - name: coroot
          image: coroot-backend:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTEN
              value: ":8080"
            - name: DATA_DIR
              value: /data
            - name: DEVELOPER_MODE
              value: "true"
            - name: STATIC_DIR
              value: /ui-static
            - name: AUTH_ANONYMOUS_ROLE
              value: Admin
            - name: PG_CONNECTION_STRING
              value: postgres://coroot:coroot@postgres:5432/coroot?sslmode=disable
            - name: GLOBAL_PROMETHEUS_USE_CLICKHOUSE
              value: "true"
            - name: GLOBAL_REFRESH_INTERVAL
              value: 15s
            - name: BOOTSTRAP_CLICKHOUSE_ADDRESS
              value: clickhouse:9000
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 36
          volumeMounts:
            - name: static
              mountPath: /ui-static
            - name: data
              mountPath: /data
        - name: frontend
          image: coroot-frontend:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: static
              mountPath: /app/static
      volumes:
        - name: static
          emptyDir: {}
        - name: data
          emptyDir: {}
