apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: coroot-dev
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: coroot-dev
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: coroot
            - name: POSTGRES_PASSWORD
              value: coroot
            - name: POSTGRES_DB
              value: coroot
          ports:
            - containerPort: 5432
              name: pg
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "coroot", "-d", "coroot"]
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          emptyDir: {}
